version: '3.8'

services:
  django:
    build: 
      context: .
      dockerfile: docker/django
    container_name: certificate-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=certificate_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=1
      - SECRET_KEY=django-insecure-=c(8r%54(b=b(-$=qe++cp*@z(os8j129!ifdrabtp4)a#aio-
    depends_on:
      - db
    networks:
      - certificate-network

  db:
    image: postgres:17
    container_name: certificate-db
    volumes:
      - certificate-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=certificate_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    networks:
      - certificate-network

volumes:
  certificate-db-data:
    external: true

networks:
  certificate-network:
    external: true 